# Generated by Django 4.2.6 on 2023-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
