# Generated by Django 4.2.6 on 2023-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_alter_post_author_alter_postcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='liked_post', to='app.userprofile'),
        ),
    ]
