# Generated by Django 4.2.6 on 2023-10-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='text',
            new_name='comment',
        ),
    ]
