# Generated by Django 4.2.6 on 2023-10-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_text_postcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
