# Generated by Django 4.2.6 on 2023-10-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-createdAt']},
        ),
    ]
