# Generated by Django 4.2.6 on 2023-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_postcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createdAt']},
        ),
    ]
