# Generated by Django 4.2.6 on 2023-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
